spring.application.name=Sit_web

spring.datasource.url=jdbc:postgresql://localhost:5432/transport
spring.datasource.username=postgres
spring.datasource.password=Samuel#01$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

    # ==========================
    # CONFIGURATION EMAIL GMAIL
    # ==========================

spring.mail.host=smtp.gmail.com
spring.mail.port=587

    # adresse email expediteur
spring.mail.username=herve010104samuel@gmail.com

    # mot de passe d'application Gmail
spring.mail.password=vktj fpvo oaoh kuzg

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

    # ORANGE SMS API
    # ============================================
    # API ORANGE SMS MADAGASCAR
    # ============================================

    # Client ID depuis le portail Orange Developer
orange.client-id=9ZyZ32y1BrNDW0n3BK8MR9brJs8GS4jI

    # Client Secret depuis le portail Orange Developer
    # (recupere-le en cliquant Show puis confirme par email)
orange.client-secret=lludMzFP23jziD23DdQ5fpDZ8j8wc1Ml2ZssO828FM0x

    # URL API Orange
orange.api.url=https://api.orange.com/smsmessaging/v1
orange.token.url=https://api.orange.com/oauth/v3/token
