spring.application.name=Sit_web
# URL de la base de données (adaptez le nom 'transport')
spring.datasource.url=jdbc:postgresql://localhost:5432/transport

#identifiants PostgreSQL (ceux configurés dans DBeaver)
spring.datasource.username=postgres
spring.datasource.password=Samuel#01$

# Driver PostgreSQL
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate configuration
# 'update' crée ou modifie automatiquement les tables selon vos classes Model
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true