spring.application.name=Sit_web

spring.datasource.url=jdbc:postgresql://localhost:5432/transport
spring.datasource.username=postgres
spring.datasource.password=Samuel#01$

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true